# Generated by Django 3.0 on 2020-09-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=200, max_digits=5),
        ),
    ]
